Repository amorriscode/tavern, pull requests merged in 2021-01, with the labels that each got.

#2 Add app scaffolding
  web/src/Routes.js
  web/src/components/Logo/Logo.js
  web/src/components/Logo/Logo.stories.js
  web/src/components/Logo/Logo.test.js
  web/src/components/Nav/Nav.js
  web/src/components/Nav/Nav.stories.js
  web/src/components/Nav/Nav.test.js
  web/src/index.css
  web/src/layouts/AppLayout/AppLayout.js
  web/src/layouts/AppLayout/AppLayout.stories.js
  web/src/layouts/AppLayout/AppLayout.test.js
  web/src/pages/HomePage/HomePage.js
  web/src/pages/HomePage/HomePage.stories.js
  web/src/pages/HomePage/HomePage.test.js
  web/tailwind.config.js
Labels: enhancement

#6 Build static code editor
  web/config/webpack.config.js
  web/package.json
  web/src/Routes.js
  web/src/components/Console/Console.js
  web/src/components/Console/Console.stories.js
  web/src/components/Console/Console.test.js
  web/src/components/Example/Example.js
  web/src/components/Example/Example.stories.js
  web/src/components/Example/Example.test.js
  web/src/components/Hint/Hint.js
  web/src/components/Hint/Hint.stories.js
  web/src/components/Hint/Hint.test.js
  web/src/components/Nav/Nav.js
  web/src/constants.js
  web/src/layouts/AppLayout/AppLayout.js
  web/src/pages/ProblemPage/ProblemPage.js
  web/src/pages/ProblemPage/ProblemPage.stories.js
  web/src/pages/ProblemPage/ProblemPage.test.js
  web/tailwind.config.js
  yarn.lock
Labels: enhancement

#8 Fix bug caused by missing variable
  web/src/pages/ProblemPage/ProblemPage.js
Labels: bug

#13 Add missing dependency and add Magic Link to .env.example
  .env.example
  api/package.json
  yarn.lock
Labels: bug, documentation

#15 Add the ability to sign up as a user
  api/db/migrations/20210109223846-create-algo-models/README.md
  api/db/migrations/20210109223846-create-algo-models/schema.prisma
  api/db/migrations/20210109223846-create-algo-models/steps.json
  api/db/migrations/20210109230008-change-difficulty-id-type/README.md
  api/db/migrations/20210109230008-change-difficulty-id-type/schema.prisma
  api/db/migrations/20210109230008-change-difficulty-id-type/steps.json
  api/db/migrations/20210109231018-add-scaffold-and-language/README.md
  api/db/migrations/20210109231018-add-scaffold-and-language/schema.prisma
  api/db/migrations/20210109231018-add-scaffold-and-language/steps.json
  api/db/migrations/20210110000339-change-scaffold-id-to-string/README.md
  api/db/migrations/20210110000339-change-scaffold-id-to-string/schema.prisma
  api/db/migrations/20210110000339-change-scaffold-id-to-string/steps.json
  api/db/migrations/20210110001404-rename-scaffold-field-in-problem/README.md
  api/db/migrations/20210110001404-rename-scaffold-field-in-problem/schema.prisma
  api/db/migrations/20210110001404-rename-scaffold-field-in-problem/steps.json
  api/db/migrations/20210110002843-remove-autoincrement-from-problem-id/README.md
  api/db/migrations/20210110002843-remove-autoincrement-from-problem-id/steps.json
  api/db/migrations/20210110010025-add-checksum-to-problem/README.md
  api/db/migrations/20210110010025-add-checksum-to-problem/schema.prisma
  api/db/migrations/20210110010025-add-checksum-to-problem/steps.json
  api/db/migrations/20210110023913-add-guild-and-transaction/README.md
  api/db/migrations/20210110023913-add-guild-and-transaction/schema.prisma
  api/db/migrations/20210110023913-add-guild-and-transaction/steps.json
  api/db/migrations/20210110050529-init/README.md
  api/db/migrations/20210110050529-init/schema.prisma
  api/db/migrations/20210110050529-init/steps.json
  api/db/migrations/migrate.lock
  api/db/schema.prisma
  api/db/seeds.js
  api/src/graphql/titles.sdl.js
  api/src/graphql/users.sdl.js
  api/src/lib/auth.js
  api/src/services/titles/titles.js
  api/src/services/titles/titles.scenarios.js
  api/src/services/titles/titles.test.js
  api/src/services/users/users.js
  api/src/services/users/users.scenarios.js
  api/src/services/users/users.test.js
  web/src/components/LoginForm/LoginForm.js
  web/src/components/SignupForm/SignupForm.js
Labels: enhancement

#3 Add code runner
  api/db/migrations/20210110091444-init/README.md
  api/db/migrations/20210110091444-init/schema.prisma
  api/db/migrations/20210110091444-init/steps.json
  api/db/migrations/migrate.lock
  api/db/schema.prisma
  api/db/seeds.js
  api/package.json
  api/src/graphql/problems.sdl.js
  api/src/graphql/solutions.sdl.js
  api/src/problems/two-sum/metadata.json
  api/src/problems/two-sum/testCases.json
  api/src/services/problems/problems.js
  api/src/services/solutions/solutions.js
  api/src/services/solutions/solutions.scenarios.js
  api/src/services/solutions/solutions.test.js
  web/src/components/Console/Console.js
  web/src/components/ProblemCell/ProblemCell.js
  yarn.lock
Labels: not ready

#18 Guild page (and more!)
  api/db/migrations/20210110103407-migration/README.md
  api/db/migrations/20210110103407-migration/schema.prisma
  api/db/migrations/20210110103407-migration/steps.json
  api/db/migrations/migrate.lock
  api/db/schema.prisma
  api/src/graphql/assignedProblems.sdl.js
  api/src/graphql/guilds.sdl.js
  api/src/problems/two-sum/metadata.json
  api/src/services/assignedProblems/assignedProblems.js
  api/src/services/assignedProblems/assignedProblems.scenarios.js
  api/src/services/assignedProblems/assignedProblems.test.js
  api/src/services/guilds/guilds.js
  web/package.json
  web/src/Routes.js
  web/src/components/AuthModal/AuthModal.js
  web/src/components/Console/Console.js
  web/src/components/DifficultyPill/DifficultyPill.js
  web/src/components/DifficultyPill/DifficultyPill.stories.js
  web/src/components/DifficultyPill/DifficultyPill.test.js
  web/src/components/Example/Example.js
  web/src/components/GuildCell/GuildCell.js
  web/src/components/GuildCell/GuildCell.mock.js
  web/src/components/GuildCell/GuildCell.stories.js
  web/src/components/GuildCell/GuildCell.test.js
  web/src/components/LoginForm/LoginForm.js
  web/src/components/Logo/Logo.js
  web/src/components/Modal/Modal.js
  web/src/components/ProblemCard/ProblemCard.js
  web/src/components/ProblemCard/ProblemCard.stories.js
  web/src/components/ProblemCard/ProblemCard.test.js
  web/src/components/ProblemCell/ProblemCell.js
  web/src/components/SignupForm/SignupForm.js
  web/src/pages/CreateGuildPage/CreateGuildPage.js
  web/src/pages/GuildPage/GuildPage.js
  web/src/pages/GuildPage/GuildPage.stories.js
  web/src/pages/GuildPage/GuildPage.test.js
  yarn.lock
Labels: enhancement

#19 Parse and display code execution results
  api/src/graphql/problems.sdl.js
  api/src/services/problems/problems.js
  web/src/components/Console/Console.js
Labels: enhancement

#20 Add leaderboard
  api/src/graphql/guilds.sdl.js
  api/src/graphql/users.sdl.js
  api/src/services/guilds/guilds.js
  api/src/services/users/users.js
  web/src/Routes.js
  web/src/components/CharacterLeaderboardCell/CharacterLeaderboardCell.js
  web/src/components/CharacterLeaderboardCell/CharacterLeaderboardCell.mock.js
  web/src/components/CharacterLeaderboardCell/CharacterLeaderboardCell.stories.js
  web/src/components/CharacterLeaderboardCell/CharacterLeaderboardCell.test.js
  web/src/components/GuildLeaderboardCell/GuildLeaderboardCell.js
  web/src/components/GuildLeaderboardCell/GuildLeaderboardCell.mock.js
  web/src/components/GuildLeaderboardCell/GuildLeaderboardCell.stories.js
  web/src/components/GuildLeaderboardCell/GuildLeaderboardCell.test.js
  web/src/components/Nav/Nav.js
  web/src/pages/LeaderboardPage/LeaderboardPage.js
  web/src/pages/LeaderboardPage/LeaderboardPage.stories.js
  web/src/pages/LeaderboardPage/LeaderboardPage.test.js
Labels: enhancement

#27 Fix bug stopping auth from working
  api/db/schema.prisma
  api/src/lib/auth.js
  api/src/services/users/users.js
  web/src/components/Logo/Logo.js
  web/src/components/Nav/Nav.js
  web/src/components/RandomCharacter/RandomCharacter.js
Labels: bug, enhancement
